**Problem Statement**

The goal of this project is to predict whether a loan will be approved or not based on applicant details such as income, education, credit history, loan amount, and other factors.

The dataset contains missing (null) values, so the first step is to clean the dataset by handling missing values. After preprocessing the data, different Machine Learning algorithms will be applied to predict the target variable (Loan_Status).

The model that provides the highest accuracy will be selected as the best-performing model.

In [3]:
import numpy as np
import pandas as pd
df = pd.read_csv("/content/train_u6lujuX_CVtuZ9i (1).csv")

In [4]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [5]:
df.tail()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [6]:
df.shape

(614, 13)

In [7]:
df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [9]:
df.isna().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [10]:
df.isna().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [11]:
df = df.dropna()

In [12]:
df.isna().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

Convsersion using LableEncoder

In [13]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

cols = ['Gender','Married','Dependents','Education','Self_Employed','Property_Area','Loan_Status']

for col in cols:
  df[col] = le.fit_transform(df[col])

In [14]:
df.dtypes

Loan_ID               object
Gender                 int64
Married                int64
Dependents             int64
Education              int64
Self_Employed          int64
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area          int64
Loan_Status            int64
dtype: object

** Define Feature Variables (X)**

X represents the input features used to train the model.
All columns except the target variable are included.
df.drop('Loan_Status', axis=1) removes the target column from the dataset.

** Define Target Variable (y)**

y represents the output variable the model needs to predict.
In this dataset, the target column is Loan_Status.

In [15]:
X = df.drop(['Loan_Status','Loan_ID'], axis=1)
Y = df['Loan_Status']

In [16]:
print(X)

     Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
1         1        1           1          0              0             4583
2         1        1           0          0              1             3000
3         1        1           0          1              0             2583
4         1        0           0          0              0             6000
5         1        1           2          0              1             5417
..      ...      ...         ...        ...            ...              ...
609       0        0           0          0              0             2900
610       1        1           3          0              0             4106
611       1        1           1          0              0             8072
612       1        1           2          0              0             7583
613       0        0           0          0              1             4583

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
1               1508.0       128.0             360.0             1.0
2                  0.0        66.0             360.0             1.0
3               2358.0       120.0             360.0             1.0
4                  0.0       141.0             360.0             1.0
5               4196.0       267.0             360.0             1.0
..                 ...         ...               ...             ...
609                0.0        71.0             360.0             1.0
610                0.0        40.0             180.0             1.0
611              240.0       253.0             360.0             1.0
612                0.0       187.0             360.0             1.0
613                0.0       133.0             360.0             0.0

     Property_Area
1                0
2                2
3                2
4                2
5                2
..             ...
609              0
610              0
611              2
612              2
613              1

[480 rows x 11 columns]

In [17]:
print(Y)

1      0
2      1
3      1
4      1
5      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 480, dtype: int64

**Split the dataset into training and testing sets using train_test_split.**

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

**Train-Test Split**

The dataset is divided into training data and testing data.

**Training Data (X_train, y_train)**

Used to train the machine learning model.

**Testing Data (X_test, y_test)**

Used to evaluate the model performance.

**test_size = 0.2**

20% of the data is used for testing.

80% of the data is used for training.

**random_state = 2**

Ensures the same data split every time the code runs.

Helps make the results reproducible.

**Logistic Regrssion **

In [19]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [20]:
y_pred = model.predict(X_test)

**Accuracy Score**

It compares the actual loan status (y_test) with the predicted loan status (y_pred).

In [21]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(Y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.75

In [22]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test, y_pred)

print(cm)

[[14 23]
 [ 1 58]]

In [23]:
import numpy as np

input_data = (1,1,0,1,0,5000,0,150,360,1,2)

# convert to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape for prediction
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)

print(prediction)

if prediction[0] == 1:
    print("Loan Approved")
else:
    print("Loan Not Approved")

[1]
Loan Approved

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

**KNN algorithm**

The parameter n_neighbors determines the number of nearest neighbors used for classification.

The predicted class is determined by the majority vote of the nearest neighbors.

In [24]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, Y_train)

KNeighborsClassifier()

In [25]:
y_pred_knn = knn.predict(X_test)

In [26]:
from sklearn.metrics import accuracy_score

print("KNN Accuracy:", accuracy_score(Y_test, y_pred_knn))

KNN Accuracy: 0.5729166666666666

**Logistic Regression performed better than KNN for this dataset.**

In [27]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(Y_test, y_pred_knn))

[[ 7 30]
 [11 48]]

In [28]:
import numpy as np

input_data = (1,1,0,1,0,5000,0,150,360,1,2)

# convert to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# prediction
prediction = knn.predict(input_data_reshaped)

print(prediction)

if prediction[0] == 1:
  print("Loan Approved")
else:
  print("Loan Not Approved")

[1]
Loan Approved

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

**Decision Tree**

In [29]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(random_state=2)

In [30]:
dt.fit(X_train, Y_train)

DecisionTreeClassifier(random_state=2)

In [31]:
y_pred_dt = dt.predict(X_test)

In [32]:
from sklearn.metrics import accuracy_score

print("Decision Tree Accuracy:", accuracy_score(Y_test, y_pred_dt))

Decision Tree Accuracy: 0.6875

In [33]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(Y_test, y_pred_dt))

[[20 17]
 [13 46]]

In [34]:
import numpy as np

input_data = (1,1,0,1,0,5000,0,150,360,1,2)

input_array = np.asarray(input_data)
input_reshaped = input_array.reshape(1,-1)

prediction = dt.predict(input_reshaped)

if prediction[0] == 1:
    print("Loan Approved")
else:
    print("Loan Not Approved")

Loan Approved

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

**Random Forest Classifier**

In [35]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train, Y_train)

RandomForestClassifier()

In [36]:
y_pred_rf = rf.predict(X_test)

In [37]:
from sklearn.metrics import accuracy_score

print("Random Forest Accuracy:", accuracy_score(Y_test, y_pred_rf))

Random Forest Accuracy: 0.7708333333333334

In [38]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(Y_test, y_pred_rf))

[[17 20]
 [ 2 57]]

In [39]:
import numpy as np

input_data = (1,1,0,1,0,5000,0,150,360,1,2)

input_array = np.asarray(input_data)
input_reshaped = input_array.reshape(1,-1)

prediction = rf.predict(input_reshaped)

if prediction[0] == 1:
    print("Loan Approved")
else:
    print("Loan Not Approved")

Loan Approved

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

**SVM (Support Vector Machine)**

In [40]:
from sklearn.svm import SVC
svm_model = SVC()

svm_model.fit(X_train, Y_train)

SVC()

In [41]:
y_pred_svm = svm_model.predict(X_test)

In [42]:
from sklearn.metrics import accuracy_score

print("SVM Accuracy:", accuracy_score(Y_test, y_pred_svm))

SVM Accuracy: 0.6041666666666666

In [43]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(Y_test, y_pred_svm))

[[ 0 37]
 [ 1 58]]

In [44]:
import numpy as np

input_data = (1,1,0,1,0,5000,0,150,360,1,2)

input_array = np.asarray(input_data)
input_reshaped = input_array.reshape(1,-1)

prediction = svm_model.predict(input_reshaped)

if prediction[0] == 1:
  print("Loan Approved")
else:
  print("Loan Not Approved")

Loan Approved

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(